### ISSUE TITLE
Offer a flatpack to have a universal linux package

### ISSUE THREAD

**Issue by thalskarth** [YACReader/yacreader#304] opened 2022-06-07 14:02 UTC
Hello,
I saw in the main site some .deb, .rpm, etc as offical instaler packages for linux but this usually works only on some linux distros and may cause dependecy conflicts. Also que archlinux AUR package requieres to recompile the libjs dependency from time to time to work.

Would it be good to have a faltpack package, this will solve the dependecies conflicts and also give an universal package wich will work the same on any distro like Fedora, Arch, Manjaro, Suse, Mint, etc at the same time.

**Comment by selmf** [comment] 2022-06-08 17:44
Duplicate of #45

**Comment by selmf** [comment] 2022-10-07 16:54
A Flatpak is now available from Flathub.

**Closed by selmf** 2022-10-07 16:54 UTC
Labels: duplicate
