### ISSUE TITLE
problem to display some grid views mode

### ISSUE THREAD

**Issue by paranoid73** [YACReader/yacreader#27] opened 2018-08-12 06:22 UTC
Hello ,
I use Arch linux recently installed YacReader Library for reading comics, grids views ( that does not work) , 
so I launched through the terminal to see what ticks and I got:
`ERROR 2018-08-10T04:09:54.799 (qrc:/qml/GridComicsView.qml:6:1: module "QtGraphicalEffects" is not installed) `
so I tried to install it , but there is a bug on my distribution about this package , I was wondering if it was possible for yacreader to propose an alternative to this package

**Comment by selmf** [comment] 2018-08-12 07:43
You're right, QtGraphicalEffects is indeed missing in the dependencies of the AUR package (I'll take care of that). But I'm not aware of any bug in that package on Arch, grid view works fine for me.

**Comment by paranoid73** [comment] 2018-08-12 15:31
default grid view work without problems , but not recent updates . 
when I change the mode (new grid views) , nothing is displayed 

![2018-08-12-125733_1366x768_scrot](https://user-images.githubusercontent.com/34898251/44003614-bd14ec06-9e44-11e8-84df-97bf21d0c581.png)

**Comment by selmf** [comment] 2018-08-12 15:48
I can't reproduce this problem on my machine. Usually a white page is caused by an error in the qml files or a missing package. Did you get any additional error messages on the console after installing QtGraphicalEffects?

**Comment by paranoid73** [comment] 2018-08-12 16:07
no just it

**Comment by selmf** [comment] 2018-08-14 09:50
This is the wrong package. You need qt5-graphicaleffects, from the main repository, NOT the AUR. The one you're trying to install is incompatible with YACReader AND the qt5 version installed on your system.

`$ sudo pacman -S qt5-graphicaleffects`

That should fix your problem. And I **really** need to fix the dependencies of the YACReader package on the AUR.

Closing this now as it is clearly not a YACReader bug.

**Closed by selmf** 2018-08-14 09:50 UTC
