### ISSUE TITLE
Escape key closes window

### ISSUE THREAD

**Issue by brainchild0** [YACReader/yacreader#121] opened 2020-03-18 05:39 UTC
It is intuitive, based on common, contemporary patterns in user interfaces, to attempt to exit full screen mode by pressing the *Escape* key. However, this key currently closes the open window. Applications closing due to this key press is an older pattern that rarely appears in modern, window-based environments.

Perhaps the *escape* key should be understood to exit full screen mode, but not any other function.

**Comment by prantlf** [comment] 2020-10-25 06:53
Using `Esc` to leave the full-screen mode might be the custom on Windows. But you use `Ctrl+Cmd+F` to enter and leave the full-screen mode on Mac, for example. The `Esc` key has no effect on the full-screen mode on Mac.

The key `Esc` is used on Windows, Mac and Linux to leave quickly an application window. It is usually a dialogue, not the main application window, but nevertheless, YACReader uses it to quickly quit the application.

Instead of changing just the handling of the `Esc` key, YACReader could consider tailoring all key handlers closer to the target platform. It means full-screen, closing the window, quitting the application on Mac, for example (`Ctrl+Cmd+F`, `Cmd+W`, `Cmd+Q`). There might be other platform-specific keys on other platforms.

However, changes in key shortcuts not should be taken lightly and done quickly, because many people got used to the existing behaviour. Especially when the keys are not configurable today.

**Comment by luisangelsm** [comment] 2020-10-25 08:45
I missed this issue.

You can change the shortcuts in YACReader, Options -> General -> Edit shortcuts -> General on the left column, and just change the key you want to use to close.

So I am closing this because even if you don't like the default you can change it.

**Closed by luisangelsm** 2020-10-25 08:45 UTC

**Comment by brainchild0** [comment] 2020-10-25 17:01
I imagine that many users would have a better experience from more intuitive defaults, rather than an expectation to configure a customization over defaults that are not intuitive. 

I understand that this change is not necessary one to be taken lightly.

**Comment by brainchild0** [comment] 2020-10-25 17:04
> Using `Esc` to leave the full-screen mode might be the custom on Windows. But you use `Ctrl+Cmd+F` to enter and leave the full-screen mode on Mac, for example. The `Esc` key has no effect on the full-screen mode on Mac.

Is this rule true for various applications generally? It would seem a cumbersome combination for simple escape operation, which is likely among the more common operations from a full-screen display mode, and of course is precisely and directly represented by the <kbd>Esc</kbd> key.

**Comment by selmf** [comment] 2020-10-25 17:14
I think the general idea behind this feature was that users use YACReaderLibrary to launch YACReader and the escape key to get back to YACReaderLibrary in a convenient way.

**Comment by luisangelsm** [comment] 2020-10-25 17:39
@brainchild0 I don't take it lightly at all, I never do with any of the feedback I get from the users. But I have learnt over the years that changing defaults causes a lot of headaches. I use YACReader myself a lot, and that is reflected in the way YACReader works because it meets my needs, as @selmf has said this behavior was intended for closing YACReader and going back to YACReaderLibrary, it seemed a good idea more than a decade ago...

**Comment by selmf** [comment] 2020-10-25 17:44
https://xkcd.com/1172/

**Comment by brainchild0** [comment] 2020-10-25 18:45
> @brainchild0 I don't take it lightly at all, I never do with any of the feedback I get from the users. But I have learnt over the years that changing defaults causes a lot of headaches. I use YACReader myself a lot, and that is reflected in the way YACReader works because it meets my needs, as @selmf has said this behavior was intended for closing YACReader and going back to YACReaderLibrary, it seemed a good idea more than a decade ago...

I'm not implying that you take it lightly, only agreeing with the earliest sentiments.

With respect to returning to the library, let me explain why it is confusing and counterintuitive for me, and why it takes some adjustment to learn. If I open an item from  the library, taking me to a windowed display of that item, and then enter full screen mode, then <kbd>Esc</kbd> most naturally returns me to the earlier windowed display, not the original library. I find it difficult that <kbd>Esc</kbd> bypasses the intermediary windowed display that was part of the earlier path.

Perhaps it would be worthwhile to consider, instead of an adjustment to the the key mapping, a change to the logic of the commands themselves, so that <kbd>Esc</kbd> (or the command it normally represents) more authentically carries the sense of returning from an immediately preceding state, whatever it might be.

**Comment by adrienbeau** [comment] 2020-11-26 18:45
As I was quite simply evaluating YACReader (again), I did not set up the library part, just opened the reader to browse some directories.

The `Esc` key shortcut has caught me *many* times by surprise. :roll_eyes: 

Glad to see it is customizable, but it is truly unusual behavior for a main window.
